# BukkitMemes Configuration File #

lolmsg: just laughed out loud!
ragequitkickmsg: You mad?
ragequitbroadcastmsg: has ragequit!
ragemsg: is raging!
facepalmmsg: just put his face to his palm.
jkmsg: is just kidding!
roflmsg: is rolling on the floor laughing!
iliketrainsmsg: likes trains!