# BukkitMemes Configuration File #

# Message for /lol #
lolmsg: just laughed out loud!

# Message for /ragequit #
ragequitkickmsg:
ragequitbroadcastmsg:

# Message for /rage #
ragemsg:

# Message for /facepalm #
facepalmmsg: