name:  BukkitMemes
main:  me.bukkitmemes.BukkitMemes.Main
version:  1.0
commands:
   lol:
     permission: bukkitmeme.lol
   ragequit:
     permission: bukkitmeme.ragequit
   rage:
     permission: bukkitmeme.rage
   facepalm:
     permission: bukkitmeme.facepalm
   bminfo:
     description: Displays what BukkitMemes version you are running.
   gf:
     permission: bukkitmeme.gf
   iliketrains:
     permission: bukkitmeme.iliketrains
   jk:
     permission: bukkitmeme.jk
   fakeop:
     permission: bukkitmeme.fakeop
     usage: /<command> <player>
   haha:
     permission: bukkitmeme.haha
     usage: /<command> <msg>
   odns:
     permission: bukkitmeme.odns
     usage: /<command> <msg>
   rofl:
     permission: bukkitmeme.rofl